name: exaiiamcl_caso1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.2
  firebase_storage: ^12.3.8
  
  # File handling
  file_picker: ^8.1.4
  
  # Video player
  video_player: ^2.9.2
  
  # Charts
  fl_chart: ^0.69.2
  
  # UI
  intl: ^0.19.0
  
  # State management
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
