name: exaiiamcl_caso2
description: "Sistema de Encuestas - Examen UIII"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  
  # Location
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Connectivity
  connectivity_plus: ^6.1.1
  
  # Charts & Maps
  fl_chart: ^0.69.0
  google_maps_flutter: ^2.9.0
  
  # UI & Utils
  provider: ^6.1.2
  intl: ^0.19.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
